// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TorreAcademy.Core.Data;

namespace TorreAcademy.Core.Migrations
{
    [DbContext(typeof(TorreAcademyDbContext))]
    [Migration("20220125190344_AddProficiency")]
    partial class AddProficiency
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TorreAcademy.Core.Entities.Experience", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdditionalInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("FromMonth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FromYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Highlighted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("Rank")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("ToMonth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToYear")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Experiences");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d673ab55-e968-45b5-ab33-598f9f9537d1"),
                            Category = 2,
                            FromMonth = "Sep",
                            FromYear = "2019",
                            Highlighted = true,
                            OrganizationId = new Guid("e5b5d7d2-02f6-4ebf-9523-d8bf8e42eb9f"),
                            Rank = 7,
                            Status = 1,
                            ToMonth = "Jul",
                            ToYear = "2021",
                            UserId = new Guid("407fcd19-a1be-4dd4-b28c-cd6a7da11748")
                        },
                        new
                        {
                            Id = new Guid("ba436729-d248-45fa-8755-c20d8335b1c9"),
                            Category = 1,
                            FromMonth = "Jan",
                            FromYear = "2007",
                            Highlighted = true,
                            OrganizationId = new Guid("c438aeba-7757-46f0-aae0-205bec5b7fe5"),
                            Rank = 1,
                            Status = 1,
                            ToMonth = "Jul",
                            ToYear = "2011",
                            UserId = new Guid("407fcd19-a1be-4dd4-b28c-cd6a7da11748")
                        },
                        new
                        {
                            Id = new Guid("c54e1acb-f388-414a-98a3-c3fbf512575d"),
                            Category = 2,
                            FromMonth = "Dec",
                            FromYear = "2017",
                            Highlighted = true,
                            OrganizationId = new Guid("04872838-77e5-442b-9432-5346de7c38c0"),
                            Rank = 6,
                            Status = 1,
                            ToMonth = "Jul",
                            ToYear = "2019",
                            UserId = new Guid("407fcd19-a1be-4dd4-b28c-cd6a7da11748")
                        },
                        new
                        {
                            Id = new Guid("a18be9fb-28ea-4e30-8bbc-c214199d2657"),
                            Category = 2,
                            FromMonth = "Aug",
                            FromYear = "2015",
                            Highlighted = true,
                            OrganizationId = new Guid("d64c44e1-2a56-475a-8a6c-32e391b6d113"),
                            Rank = 5,
                            Status = 1,
                            ToMonth = "Nov",
                            ToYear = "2017",
                            UserId = new Guid("407fcd19-a1be-4dd4-b28c-cd6a7da11748")
                        },
                        new
                        {
                            Id = new Guid("45ace798-fcec-4c95-bfd0-ffaafd80814d"),
                            Category = 2,
                            FromMonth = "Nov",
                            FromYear = "2013",
                            Highlighted = true,
                            OrganizationId = new Guid("f2b388df-350a-44da-b27a-c674955902ae"),
                            Rank = 4,
                            Status = 1,
                            ToMonth = "Jul",
                            ToYear = "2015",
                            UserId = new Guid("407fcd19-a1be-4dd4-b28c-cd6a7da11748")
                        },
                        new
                        {
                            Id = new Guid("a4eaa797-0c28-42a0-b3d0-f8bc30ef341d"),
                            Category = 2,
                            FromMonth = "Aug",
                            FromYear = "2012",
                            Highlighted = true,
                            OrganizationId = new Guid("53fd3177-8954-434e-a41d-e93ee8962c6e"),
                            Rank = 3,
                            Status = 1,
                            ToMonth = "Oct",
                            ToYear = "2013",
                            UserId = new Guid("407fcd19-a1be-4dd4-b28c-cd6a7da11748")
                        },
                        new
                        {
                            Id = new Guid("4021a280-9885-403d-955e-1c041db425b9"),
                            Category = 2,
                            FromMonth = "Sep",
                            FromYear = "2011",
                            Highlighted = true,
                            OrganizationId = new Guid("c1bf1539-a695-4722-ad97-47529029fe96"),
                            Rank = 2,
                            Status = 1,
                            ToMonth = "Jul",
                            ToYear = "2012",
                            UserId = new Guid("407fcd19-a1be-4dd4-b28c-cd6a7da11748")
                        },
                        new
                        {
                            Id = new Guid("f37a4c61-3123-4660-8c7a-ba693bfc2b0e"),
                            Category = 2,
                            FromMonth = "Jan",
                            FromYear = "2015",
                            Highlighted = true,
                            OrganizationId = new Guid("e5b5d7d2-02f6-4ebf-9523-d8bf8e42eb9f"),
                            Rank = 4,
                            Status = 1,
                            ToMonth = "Jan",
                            ToYear = "2022",
                            UserId = new Guid("50f9ee73-8522-4303-8422-957fa1537bc4")
                        },
                        new
                        {
                            Id = new Guid("8cd498a9-7f9f-42b2-9177-77fa8797193a"),
                            Category = 1,
                            FromMonth = "Jan",
                            FromYear = "2000",
                            Highlighted = true,
                            OrganizationId = new Guid("c438aeba-7757-46f0-aae0-205bec5b7fe5"),
                            Rank = 1,
                            Status = 1,
                            ToMonth = "Jul",
                            ToYear = "2004",
                            UserId = new Guid("50f9ee73-8522-4303-8422-957fa1537bc4")
                        },
                        new
                        {
                            Id = new Guid("25486295-fd51-4542-9187-a57bff7b3ca7"),
                            Category = 2,
                            FromMonth = "Aug",
                            FromYear = "2009",
                            Highlighted = true,
                            OrganizationId = new Guid("d64c44e1-2a56-475a-8a6c-32e391b6d113"),
                            Rank = 3,
                            Status = 1,
                            ToMonth = "Dec",
                            ToYear = "2014",
                            UserId = new Guid("50f9ee73-8522-4303-8422-957fa1537bc4")
                        },
                        new
                        {
                            Id = new Guid("24f96c26-1590-42b9-a97d-25bf60c9a7c8"),
                            Category = 2,
                            FromMonth = "Jan",
                            FromYear = "2005",
                            Highlighted = true,
                            OrganizationId = new Guid("f2b388df-350a-44da-b27a-c674955902ae"),
                            Rank = 2,
                            Status = 1,
                            ToMonth = "Jul",
                            ToYear = "2009",
                            UserId = new Guid("50f9ee73-8522-4303-8422-957fa1537bc4")
                        },
                        new
                        {
                            Id = new Guid("9fca72a8-10f5-42db-86f1-df454657de90"),
                            Category = 2,
                            FromMonth = "Jan",
                            FromYear = "2019",
                            Highlighted = true,
                            OrganizationId = new Guid("04872838-77e5-442b-9432-5346de7c38c0"),
                            Rank = 3,
                            Status = 1,
                            ToMonth = "Jul",
                            ToYear = "2021",
                            UserId = new Guid("30095048-1935-44e2-bef9-b450b8e34135")
                        },
                        new
                        {
                            Id = new Guid("734c4986-fdca-4006-a055-f0f4edbc8741"),
                            Category = 2,
                            FromMonth = "Apr",
                            FromYear = "2015",
                            Highlighted = true,
                            OrganizationId = new Guid("d64c44e1-2a56-475a-8a6c-32e391b6d113"),
                            Rank = 2,
                            Status = 1,
                            ToMonth = "Dec",
                            ToYear = "2018",
                            UserId = new Guid("30095048-1935-44e2-bef9-b450b8e34135")
                        },
                        new
                        {
                            Id = new Guid("efc029e8-b75e-4e6a-847c-348a05f6575e"),
                            Category = 2,
                            FromMonth = "Jan",
                            FromYear = "2010",
                            Highlighted = true,
                            OrganizationId = new Guid("f2b388df-350a-44da-b27a-c674955902ae"),
                            Rank = 1,
                            Status = 1,
                            ToMonth = "Mar",
                            ToYear = "2015",
                            UserId = new Guid("30095048-1935-44e2-bef9-b450b8e34135")
                        },
                        new
                        {
                            Id = new Guid("a70971dd-845b-425a-98bf-dd6ee5e23f7d"),
                            Category = 2,
                            FromMonth = "Feb",
                            FromYear = "2020",
                            Highlighted = true,
                            OrganizationId = new Guid("04872838-77e5-442b-9432-5346de7c38c0"),
                            Rank = 2,
                            Status = 1,
                            ToMonth = "Jul",
                            ToYear = "2021",
                            UserId = new Guid("404321a7-3229-4bfa-b795-e9c616ca99a6")
                        },
                        new
                        {
                            Id = new Guid("67cc76b5-2571-455c-aa7c-87f60336a7b2"),
                            Category = 2,
                            FromMonth = "Jan",
                            FromYear = "2018",
                            Highlighted = true,
                            OrganizationId = new Guid("d64c44e1-2a56-475a-8a6c-32e391b6d113"),
                            Rank = 1,
                            Status = 1,
                            ToMonth = "Jan",
                            ToYear = "2020",
                            UserId = new Guid("404321a7-3229-4bfa-b795-e9c616ca99a6")
                        });
                });

            modelBuilder.Entity("TorreAcademy.Core.Entities.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublicId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Organizations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e5b5d7d2-02f6-4ebf-9523-d8bf8e42eb9f"),
                            Name = "Torre",
                            PublicId = "Torre",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("c438aeba-7757-46f0-aae0-205bec5b7fe5"),
                            Name = "AmericanInternationUniversityBangladesh",
                            PublicId = "American Internation University Bangladesh",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("04872838-77e5-442b-9432-5346de7c38c0"),
                            Name = "7 Medical Systems",
                            PublicId = "7MedicalSystems",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("d64c44e1-2a56-475a-8a6c-32e391b6d113"),
                            Name = "Aprosoft",
                            PublicId = "Aprosoft",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("f2b388df-350a-44da-b27a-c674955902ae"),
                            Name = "Brain Station 23",
                            PublicId = "BrainStation23",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("53fd3177-8954-434e-a41d-e93ee8962c6e"),
                            Name = "Hashkloud",
                            PublicId = "Hashkloud",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("c1bf1539-a695-4722-ad97-47529029fe96"),
                            Name = "Microsoft",
                            PublicId = "Microsoft",
                            Status = 1
                        });
                });

            modelBuilder.Entity("TorreAcademy.Core.Entities.Proficiency", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Proficiencies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cc82bee1-f49e-4b53-a062-b666e83ad6d6"),
                            Name = "Master / Influencer",
                            Order = 1,
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("d67b3c14-da66-4ebd-a5f9-6087b33f4649"),
                            Name = "Expert",
                            Order = 2,
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("55bf6696-fc88-4b9e-a01f-8670d4d627c1"),
                            Name = "Proficient",
                            Order = 3,
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("ac095f03-1349-48aa-94aa-ab8f23021f30"),
                            Name = "Novice",
                            Order = 4,
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("6e22f4b3-dedd-40f4-99b1-1a419afb0415"),
                            Name = "No Experience",
                            Order = 5,
                            Status = 1
                        });
                });

            modelBuilder.Entity("TorreAcademy.Core.Entities.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Skills");

                    b.HasData(
                        new
                        {
                            Id = new Guid("750ee1f7-4658-433c-8002-fd83c2c16732"),
                            Description = "Software Development",
                            Name = "Software Development",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("65cd41a7-6b3b-4c05-9fcc-3ca364b2b841"),
                            Description = "Web Development",
                            Name = "Web Development",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("c09d1c06-41fb-48ae-8c76-70f66edc8804"),
                            Description = "Full Stack Development",
                            Name = "Full Stack Development",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("eab66851-38a4-4f05-b9eb-4727950145e6"),
                            Description = "Rest API",
                            Name = "Rest API",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("78335ce5-1e40-4f27-bb6f-136de91d523b"),
                            Description = "C#",
                            Name = "C#",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("95a0cd63-9bcd-4e18-8ac5-a96a3b6e5cb5"),
                            Description = "ASP.NET",
                            Name = "ASP.NET",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("d1a7df8f-f94b-449f-86ae-246c3d1bd6e8"),
                            Description = "React",
                            Name = "React",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("3d9331b5-40cd-47cb-885a-02d3653ee50c"),
                            Description = "JavaScript",
                            Name = "JavaScript",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("3d652a05-25a9-4d81-84f6-43237170db0c"),
                            Description = "Back End",
                            Name = "Back End",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("2f9831e8-7eff-4659-aec5-ddc903135a06"),
                            Description = "Java",
                            Name = "Java",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("fbb42887-8c85-4e15-b40f-7f14579be6e6"),
                            Description = "DevOps",
                            Name = "DevOps",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("9d21ad81-dd79-4cfe-8029-99658ce8488d"),
                            Description = "Node.js",
                            Name = "Node.js",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("6e66fb3d-d540-459b-b3c3-7d9ad834588e"),
                            Description = "Vue.js",
                            Name = "Vue.js",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("e98253b2-2ae3-477c-8841-344fe706ac1b"),
                            Description = "Ruby",
                            Name = "Ruby",
                            Status = 1
                        },
                        new
                        {
                            Id = new Guid("0eebe5e0-04c8-4eea-9d93-ef75bba84686"),
                            Description = "Azure",
                            Name = "Azure",
                            Status = 1
                        });
                });

            modelBuilder.Entity("TorreAcademy.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("407fcd19-a1be-4dd4-b28c-cd6a7da11748"),
                            CreatedDate = new DateTime(2022, 1, 26, 1, 3, 43, 510, DateTimeKind.Local).AddTicks(9718),
                            Email = "khabir.aiub@gmail.com",
                            FirstName = "Muhammad Khabir",
                            LastName = "Uddin",
                            Phone = "+8801914328355",
                            Status = 1,
                            UserName = "khabir"
                        },
                        new
                        {
                            Id = new Guid("50f9ee73-8522-4303-8422-957fa1537bc4"),
                            CreatedDate = new DateTime(2022, 1, 26, 1, 3, 43, 512, DateTimeKind.Local).AddTicks(9787),
                            Email = "Torrenegra@gmail.com",
                            FirstName = "Alexander",
                            LastName = "Torrenegra",
                            Phone = "+565464564565",
                            Status = 1,
                            UserName = "torrenegra"
                        },
                        new
                        {
                            Id = new Guid("30095048-1935-44e2-bef9-b450b8e34135"),
                            CreatedDate = new DateTime(2022, 1, 26, 1, 3, 43, 512, DateTimeKind.Local).AddTicks(9885),
                            Email = "Martinez@gmail.com",
                            FirstName = "Alex",
                            LastName = "Martinez",
                            Phone = "+456456456456",
                            Status = 1,
                            UserName = "martinez"
                        },
                        new
                        {
                            Id = new Guid("404321a7-3229-4bfa-b795-e9c616ca99a6"),
                            CreatedDate = new DateTime(2022, 1, 26, 1, 3, 43, 512, DateTimeKind.Local).AddTicks(9894),
                            Email = "Rex@gmail.com",
                            FirstName = "Jessie",
                            LastName = "Uddin",
                            Phone = "+44564564562",
                            Status = 1,
                            UserName = "rex"
                        });
                });

            modelBuilder.Entity("TorreAcademy.Core.Entities.UserOrganization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("UserId");

                    b.ToTable("UserOrganizations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("accc4577-ade3-4293-9404-415623d1ff46"),
                            OrganizationId = new Guid("e5b5d7d2-02f6-4ebf-9523-d8bf8e42eb9f"),
                            Status = 1,
                            UserId = new Guid("407fcd19-a1be-4dd4-b28c-cd6a7da11748")
                        },
                        new
                        {
                            Id = new Guid("c0718d07-adac-4b9b-97fd-4e7cedaa44d6"),
                            OrganizationId = new Guid("c438aeba-7757-46f0-aae0-205bec5b7fe5"),
                            Status = 1,
                            UserId = new Guid("407fcd19-a1be-4dd4-b28c-cd6a7da11748")
                        },
                        new
                        {
                            Id = new Guid("2e7ff23e-9476-4a55-a13e-a6d8c1166bca"),
                            OrganizationId = new Guid("04872838-77e5-442b-9432-5346de7c38c0"),
                            Status = 1,
                            UserId = new Guid("407fcd19-a1be-4dd4-b28c-cd6a7da11748")
                        },
                        new
                        {
                            Id = new Guid("4efd764f-b15e-4fb1-9603-c53bf07ce468"),
                            OrganizationId = new Guid("d64c44e1-2a56-475a-8a6c-32e391b6d113"),
                            Status = 1,
                            UserId = new Guid("407fcd19-a1be-4dd4-b28c-cd6a7da11748")
                        },
                        new
                        {
                            Id = new Guid("b35113d5-f2c5-4109-8c63-8bd17085360f"),
                            OrganizationId = new Guid("f2b388df-350a-44da-b27a-c674955902ae"),
                            Status = 1,
                            UserId = new Guid("407fcd19-a1be-4dd4-b28c-cd6a7da11748")
                        },
                        new
                        {
                            Id = new Guid("0368a824-b091-4ea4-bd2e-a62d14802791"),
                            OrganizationId = new Guid("53fd3177-8954-434e-a41d-e93ee8962c6e"),
                            Status = 1,
                            UserId = new Guid("407fcd19-a1be-4dd4-b28c-cd6a7da11748")
                        },
                        new
                        {
                            Id = new Guid("b4667b5c-7f55-4d51-b110-309a6642fcfa"),
                            OrganizationId = new Guid("c1bf1539-a695-4722-ad97-47529029fe96"),
                            Status = 1,
                            UserId = new Guid("407fcd19-a1be-4dd4-b28c-cd6a7da11748")
                        },
                        new
                        {
                            Id = new Guid("17d89680-fef6-4793-aa4a-9aa46340adc8"),
                            OrganizationId = new Guid("e5b5d7d2-02f6-4ebf-9523-d8bf8e42eb9f"),
                            Status = 1,
                            UserId = new Guid("50f9ee73-8522-4303-8422-957fa1537bc4")
                        },
                        new
                        {
                            Id = new Guid("f27da8e3-718f-4bdf-bfaf-e2214fe79a1b"),
                            OrganizationId = new Guid("04872838-77e5-442b-9432-5346de7c38c0"),
                            Status = 1,
                            UserId = new Guid("50f9ee73-8522-4303-8422-957fa1537bc4")
                        },
                        new
                        {
                            Id = new Guid("5c6fd1ed-0e04-4e3d-80d4-e1060740a5ba"),
                            OrganizationId = new Guid("d64c44e1-2a56-475a-8a6c-32e391b6d113"),
                            Status = 1,
                            UserId = new Guid("50f9ee73-8522-4303-8422-957fa1537bc4")
                        },
                        new
                        {
                            Id = new Guid("076d7c47-3be2-4aa3-8fb1-ed5be14d5e82"),
                            OrganizationId = new Guid("f2b388df-350a-44da-b27a-c674955902ae"),
                            Status = 1,
                            UserId = new Guid("50f9ee73-8522-4303-8422-957fa1537bc4")
                        },
                        new
                        {
                            Id = new Guid("2e1c8c3a-e8c2-4df6-b345-bbf08f8b8daf"),
                            OrganizationId = new Guid("04872838-77e5-442b-9432-5346de7c38c0"),
                            Status = 1,
                            UserId = new Guid("30095048-1935-44e2-bef9-b450b8e34135")
                        },
                        new
                        {
                            Id = new Guid("515d1297-9a92-4fd6-8c17-3f7a807c9ed6"),
                            OrganizationId = new Guid("d64c44e1-2a56-475a-8a6c-32e391b6d113"),
                            Status = 1,
                            UserId = new Guid("30095048-1935-44e2-bef9-b450b8e34135")
                        },
                        new
                        {
                            Id = new Guid("8df3381e-b33d-4e89-860b-b25fd036162d"),
                            OrganizationId = new Guid("f2b388df-350a-44da-b27a-c674955902ae"),
                            Status = 1,
                            UserId = new Guid("30095048-1935-44e2-bef9-b450b8e34135")
                        },
                        new
                        {
                            Id = new Guid("3e239fe6-a066-4ece-bc91-947fcc28fac7"),
                            OrganizationId = new Guid("04872838-77e5-442b-9432-5346de7c38c0"),
                            Status = 1,
                            UserId = new Guid("404321a7-3229-4bfa-b795-e9c616ca99a6")
                        },
                        new
                        {
                            Id = new Guid("20fed92b-bf7f-4096-b8e5-10fe3d235011"),
                            OrganizationId = new Guid("d64c44e1-2a56-475a-8a6c-32e391b6d113"),
                            Status = 1,
                            UserId = new Guid("404321a7-3229-4bfa-b795-e9c616ca99a6")
                        });
                });

            modelBuilder.Entity("TorreAcademy.Core.Entities.UserSkill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProficiencyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProficiencyId");

                    b.HasIndex("SkillId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("UserSkills");
                });

            modelBuilder.Entity("TorreAcademy.Core.Entities.Experience", b =>
                {
                    b.HasOne("TorreAcademy.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("TorreAcademy.Core.Entities.UserOrganization", b =>
                {
                    b.HasOne("TorreAcademy.Core.Entities.Organization", "Organization")
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TorreAcademy.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TorreAcademy.Core.Entities.UserSkill", b =>
                {
                    b.HasOne("TorreAcademy.Core.Entities.Proficiency", "Proficiency")
                        .WithMany()
                        .HasForeignKey("ProficiencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TorreAcademy.Core.Entities.Skill", "Skill")
                        .WithOne("UserSkill")
                        .HasForeignKey("TorreAcademy.Core.Entities.UserSkill", "SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TorreAcademy.Core.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
